/**
 * Deterministic, stable URL slug for storefront product pages.
 * Must stay identical to any slug generated by the ingestion pipeline so the
 * ES document always agrees with the Postgres row for the same product.
 */
export function slugify(text) {
  return String(text ?? "")
    .normalize("NFKD")
    .replace(/æ/gi, "ae")
    .replace(/ø/gi, "o")
    .replace(/&/g, " and ")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 130);
}